# Generated by Django 5.0.6 on 2024-09-09 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='SeminarHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=255)),
                ('hall_name', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('audio_system', models.BooleanField(default=False)),
                ('projector', models.BooleanField(default=False)),
                ('internet_wifi', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='admin_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='seminarhall',
            constraint=models.UniqueConstraint(fields=('institute_name', 'hall_name'), name='unique_hall_per_institute'),
        ),
    ]
