# Generated by Django 5.0.6 on 2024-09-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_data',
            name='user',
        ),
    ]
