# Generated by Django 5.0.6 on 2024-09-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0002_remove_admin_data_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_data',
            name='institute_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
