# Generated by Django 5.0.6 on 2024-09-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0003_admin_data_institute_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_data',
            name='institute_name',
            field=models.CharField(blank=True, choices=[('Institute1', 'CSPIT'), ('Institute2', 'DEPSTAR'), ('Institute3', 'RPCP'), ('Institute4', 'PDPIAS'), ('Institute5', 'Ashok and Rita patel institute of physiotherapy'), ('Institute6', 'IIIM'), ('Institute7', 'BDIPS'), ('Institute8', 'CMPICA'), ('Institute9', 'Manikaka Topawala Institute of Nursing')], max_length=255, null=True, unique=True),
        ),
    ]
