# Generated by Django 5.0.6 on 2024-09-10 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0006_remove_bookingrequest_time_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingsystem.admin_data'),
        ),
        migrations.AlterField(
            model_name='admin_data',
            name='institute_name',
            field=models.CharField(blank=True, choices=[('CSPIT', 'CSPIT'), ('DEPSTAR', 'DEPSTAR'), ('RPCP', 'RPCP'), ('PDPIAS', 'PDPIAS'), ('Ashok and Rita patel institute of physiotherapy', 'Ashok and Rita patel institute of physiotherapy'), ('IIIM', 'IIIM'), ('BDIPS', 'BDIPS'), ('CMPICA', 'CMPICA'), ('Manikaka Topawala Institute of Nursing', 'Manikaka Topawala Institute of Nursing')], max_length=255, null=True, unique=True),
        ),
    ]
